name: Deploy to Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. paths-filterアクションを使用して、特定のディレクトリに変更があったかを確認
      - name: Check for changes in 'database/migrations/'
        id: migrations_check
        uses: dorny/paths-filter@v2
        with:
          filters: |
            migrations:
              - 'database/migrations/**'

      # 3. リモートサーバーにSSH接続してgit pullを実行
      - name: Pull latest code from git repository
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ordermade/yakyumare-be
            git pull origin production

      # 4. キャッシュ関連の処理
      - name: Clear cache and optimize
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ordermade/yakyumare-be
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache

      # 5. マイグレーションがあれば実行
      - name: Run migrations if available
        if: ${{ steps.migrations_check.outputs.migrations == 'true' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ordermade/yakyumare-be
            php artisan migrate --force
